name: docs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Install Doxygen
        run: |
          sudo apt-get install -y doxygen;
          (cd src; doxygen Doxyfile)
