name: docs
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@1.9.8
        with:
          doxyfile-path: Doxyfile
          working-directory: src
